name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Mapalokalala
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github-light
            output/github-contribution-grid-snake-dark.svg?color_snake=#00B4D8&palette=github-dark

      - name: Push output to repository
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
